[package]
name = "gb-wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb_core = { path = "../gb_core" }
wgpu = "0.10.1"
pixels = "0.6.0"
winit = "0.25.0"
smol = "*"
