[package]
name = "gb_core"
version = "0.1.0"
authors = ["Ben Engdahl <bengdahl341@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4"
gb_cpu = { path = "../gb_cpu" }
